---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperopt-mongo
  name: hyperopt-mongo
  namespace: datascience
spec:
  ports:
    - name: "mongo-db"
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: hyperopt-mongo
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperopt-workers
  namespace: datascience
  labels:
    app: hyperopt-workers
spec:
  template:
    metadata:
      name: hyperopt-workers
      namespace: datascience
      labels:
        app: hyperopt-workers
    spec:
      containers:
        - name: hyperkops-worker
          image:  foo:foo
          imagePullPolicy: Never
          resources:
            limits:
              memory: "300Mi"
              cpu: "200m"
            requests:
              memory: "300Mi"
              cpu: "200m"
          env:
            - name: MONGO_DB_ADDRESS
              value: "hyperopt-mongo"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: TRIALS_DB
              value: "models"
#            - name: HYPEROPT_ARG_POLLING_INTERVAL
#              value: "0.1"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperopt-mongo
  namespace: datascience
  labels:
    app: hyperopt-mongo
spec:
  replicas: 1
  template:
    metadata:
      name: hyperopt-mongo
      namespace: datascience
      labels:
        app: hyperopt-mongo
    spec:
      containers:
        - name: mongo-db
          image: mongo
#          resources:
#            limits:
#              cpu: 500
#            requests:
#              cpu: 500

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperopt-stale-job-monitor
  namespace: datascience
  labels:
    app: hyperopt-stale-job-monitor
spec:
  replicas: 1
  template:
    metadata:
      name: hyperopt-stale-job-monitor
      namespace: datascience
      labels:
        app: hyperopt-stale-job-monitor
    spec:
      containers:
        - name: hyerkops-monitor
          image: hyperkops:hyperkops-monitor
          imagePullPolicy: Never
          env:
            - name: MONGO_DB_ADDRESS
              value: "hyperopt-mongo"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: UPDATE_INTERVAL
              value: "5"
            - name: TRIALS_TIMEOUT_INTERVAL
              value: "15"
            - name: LOGLEVEL
              value: "DEBUG"
            - name: TRIALS_DB
              value: "models"
            - name: TRIALS_COLLECTION
              value: "models"
            - name: NAMESPACE
              value: "datascience"
            - name: LABEL_SELECTOR
              value: "app=hyperopt-workers"
          resources:
            limits:
              cpu: "100m"
              memory: "200Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"
      restartPolicy: Always
#---
#apiVersion: extensions/v1beta1
#kind: Deployment
#metadata:
#  name: hyperopt-trials-content
#  namespace: datascience
#  labels:
#    app: hyperopt-trials-content
#spec:
#  replicas: 1
#  template:
#    metadata:
#      name: hyperopt-trials-content
#      namespace: datascience
#      labels:
#        app: hyperopt-trials-content
#    spec:
#      containers:
#        - name: hyperopt-trials-content
#          image: "{{ getenv "AWS_ACCOUNT_ID" }}.dkr.ecr.{{ getenv "AWS_DEFAULT_REGION" }}.amazonaws.com/hipagesgroup/radagast:{{ getenv "TOOLS_TAG" }}"
#          command:
#            - ./launch_model_fitter.sh
#          args: ["mongo_content_logging"]
#          env:
#            - name: MONGO_DB_ADDRESS
#              value: "hyperopt-mongo.datascience.svc.cluster.local"
#            - name: MONGO_DB_PORT
#              value: "27017"
#            - name: LOGLEVEL
#              value: "DEBUG"
#      restartPolicy: Always
##############################
# Worker Autoscaling
##############################
#---
#apiVersion: autoscaling/v2beta1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: hyperopt-workers
#  namespace: datascience
#  labels:
#    app: hyperopt-workers
#spec:
#  scaleTargetRef:
#    apiVersion: extensions/v1beta1
#    kind: Deployment
#    name: hyperopt-workers
#  minReplicas: 1
#  maxReplicas: 50
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 75
##########################################################
##########################################################