---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hyperkops-example
  namespace: datascience
  labels:
    app: hyperkops-example
spec:
  replicas: 1
  template:
    metadata:
      name: hyperkops-example
      namespace: datascience
      labels:
        app: hyperkops-example
    spec:
      containers:
        - name: hyperkops-example
          image: hyperkops:hyperkops-examples
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_DB_ADDRESS
              value: "hyperopt-mongo"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: LOGLEVEL
              value: "DEBUG"
            - name: TRIALS_DB
              value: "models"
            - name: TRIALS_COLLECTION
              value: "models"
            - name: NUM_EVAL_STEPS
              value: "1000"
            - name: MULTIPLIER
              value: "2"
      restartPolicy: Always

