---
apiVersion: batch/v1
kind: Job
metadata:
  name: hyperkops-example
  namespace: datascience
  labels:
    app: hyperkops-example
spec:
  template:
    metadata:
      name: hyperkops-example
      namespace: datascience
      labels:
        app: hyperkops-example
    spec:
      containers:
        - name: hyperkops-example
          image: hipages/hyperkops-example:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "500m"
              memory: "500Mi"
          env:
            - name: MONGO_DB_ADDRESS
              value: "hyperkops-mongo.datascience.svc.cluster.local"
            - name: MONGO_DB_PORT
              value: "27017"
            - name: LOGLEVEL
              value: "DEBUG"
            - name: TRIALS_DB
              value: "models"
            - name: TRIALS_COLLECTION
              value: "jobs"
            - name: NUM_EVAL_STEPS
              value: "10"
            - name: MULTIPLIER
              value: "2"
            - name: PYTHONUNBUFFERED
              value: "1"
      restartPolicy: OnFailure

